### PR TITLE
Use container-based infrastructure for faster build

### PR DESCRIPTION
**Pull request by shinnn**
http://docs.travis-ci.com/user/workers/container-based-infrastructure/

### CODE REVIEW

**Comment by shinnn** [comment]
Related official blog post: [The Travis CI Blog: Faster Builds with Container-Based Infrastructure and Docker](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/)

**Comment by nkzawa** [comment]
:+1:

**Comment by shinnn** [comment]
Friendly ping :)

**Comment by rauchg** [comment]
Thank you shinnn :)

**Pull request merged**
