### PR TITLE
Cookie Improvements

### PR DESCRIPTION
**Pull request by dlimkin**
- fix cookiePath empty bug;
- remove unused readFileSync require;
- add dependence cookie module;
- Set-Cookie refactor with cookie module;
- add options cookieHttpOnly;

### CODE REVIEW

**Comment by westy92** [comment]
+1 for the `cookieHttpOnly` option.

**Comment by darrachequesne** [comment]
@dlimkin could you please fix the conflicts and document the `cookieHttpOnly` option please?

**Comment by dlimkin** [comment]
Done!
- cookiePath option default set to '/';
- cookieHttpOnly option default set to true;
- add documentation for the cookieHttpOnly option;
- added compatibility with node v7;

**Comment by darrachequesne** [comment]
Merged as 60780e2fb7c7ce8e6a990f65fe55e4334daec615 and https://github.com/socketio/engine.io/pull/441. Thanks a lot!

**Pull request closed without merging**
