### PR TITLE
enable session sharing via redis

### PR DESCRIPTION
**Pull request by MoLow**
I was wondering if is is possible to add this feature into engine.io, since it is very hard to run a engine.io/socket.io using nodes native cluster module (I use pm2 which uses it), and the only workarounds I found are pretty hackey.

this obviously adds a dependency for the redis module which is not allways needed, mabe there is a solution for that, but this enables engine.io to work in an un-statfull way.

i'd love to get feedback about this feature.

### CODE REVIEW

**Comment by MoLow** [comment]
Well, I think maybe instead of providing as an option the host and the port of redis,
a function which is a getter/setter/deleter for existing sessions (which I implemented as Server.prototype.client) could be a better solution.

will that be better?

**Comment by zbigg** [comment]
Hi,
Thanks for this PR, i also needed cross-process socket-sharing in socket.io/engine.io like this, but assumed it's too bit big task.

This PR does one thing - session sharing in redis - cool. But IMHO, it's not enough.

I this this PR is missing one important feature - buffer sharing, without it it's just half of proper "multi-process support".

What i mean, is that `socket.send` may buffer packets. And this buffer is in one particular process that at this time decided to send something. In reality, next XHR-poll request (or WS reconnect) may arrive at other process and thus message is missed.
In wost weird case, this packet may be drained (delivered to client) later out-of-order because client happened to connect again to process with stale buffer.

Nevertheless, i think that this patch may work for particular scenarios where messages may be missed (and reordered) like in simple signaling that triggers client to update its resources (this may be also my case!).

If that patch would be followed up to custom session/buffer store socket.io/engine.io may work behind ELB/HAProxy without sticky sessions which would be a huge win (AFAIR, no WS library supports it out-of-box without hacks).

> function which is a getter/setter/deleter for existing sessions

Agree in general, this should be pluggable mechanism which defaults to in-mem storage.

**Comment by darrachequesne** [comment]
@MoLow thanks for the huge work! That is indeed a very interesting feature.

First, if we want to merge this, I think we should make it work a bit like `socket.io-adapter` and `socket.io-redis`, with a default in-memory storage as noted by @zbigg. That'll need a bit of testing too :smile: 

Note: I'm still trying the assess impact on socket.io above

**Comment by MoLow** [comment]
Wow, thanks for the feedback. 

so @zbigg you are basically saying it is impossible to manage multi-process/thread websocekts in nodejs, without putting the processes behind some kind of proxy?

> Agree in general, this should be pluggable mechanism which defaults to in-mem storage

dose this any benefit besides enabling stickey sessions? as @zbigg any other solution than in-memory session store could potentially mess up buffer ordering

**Comment by darrachequesne** [comment]
@MoLow I think what @zbigg suggested is that the socket's `writeBuffer`, storing the packets waiting to be sent to the client, should also be persisted in Redis.

**Comment by darrachequesne** [comment]
@MoLow @zbigg I wonder whether this is even possible. I mean, handshake and buffer could indeed be shared between servers, but what about messages sent from the client, which can eventually reach any server? In that case, where should the `on('<event>')` be triggered?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Pull request closed without merging**
