### PR TITLE
Upgrade ws to 1.0.1

### LINKED ISSUE #373: Upgrade to ws@1.0.0
Karma really needs this, as the current ws version is broken when used in combination with core-js. See https://github.com/karma-runner/karma/issues/1768#issuecomment-168114290 and https://github.com/websockets/ws/issues/645 for details on the bug and https://github.com/websockets/ws/releases/tag/1.0.0 for details on the release

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Closes #373

### CODE REVIEW

**Comment by addaleax** [comment]
Maybe update this to 1.0.1 as per #375?

**Comment by apollocatlin** [comment]
+1 for 1.0.1

**Comment by Dignifiedquire** [comment]
Done

**Comment by nuclearace** [comment]
:+1:  @rauchg

**Comment by apollocatlin** [comment]
+1

**Comment by rauchg** [comment]
Done in `-client` too. Thanks

**Pull request merged**
