### PR TITLE
Update uws optional

### PR DESCRIPTION
**Pull request by kievechua**
### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour
Unable to install engine.io without throwing error

### New behaviour
engine.io can be install without error

### Other information (e.g. related issues)
All test passed
All old versions is unpublished
https://github.com/uWebSockets/uWebSockets/issues/551
https://github.com/npm/npm/issues/16178

### CODE REVIEW

**Comment by darrachequesne** [comment]
@kievechua thanks!

**Comment by barryvdh** [comment]
As the old versions from uws are actually removed, should a new version of engine.io be tagged, and socket.io be updated to use the new version + tagged? Otherwise `uws` won't be installed at all for current releases, right? (Although it is still optional, it would give warnings)

**Comment by kapouer** [comment]
Best thing to do, considering the situation is to use `"uws": "*"` and let npm install latest version...

**Comment by darrachequesne** [comment]
@kapouer what's the point of versioning then?

**Comment by barryvdh** [comment]
Yeah that would break with breaking changes., bad idea.

**Pull request merged**
