### PR TITLE
Add proper response when handleUpgrade fails

### PR DESCRIPTION
**Pull request by darrachequesne**
### The kind of change this PR does introduce

* **a bug fix**

### Current behaviour

When the `verify` method fails, the current implementation closes the connection immediately, which is understood by some proxy (such as nginx) as if the server was not available (resulting in "upstream
prematurely closed connection while reading response header from upstream" error).

### New behaviour

That commit make sure a proper response is sent before closing the connection.

### Other information (e.g. related issues)

Fixes https://github.com/socketio/engine.io/issues/283
Closes https://github.com/socketio/engine.io/pull/454, fixes https://github.com/socketio/socket.io/issues/2779

### CODE REVIEW

**Comment by darrachequesne** [comment]
cc @julianlam @beatjoerg @vostrik

**Comment by vostrik** [comment]
Thank you!
Please, update npm package:
https://www.npmjs.com/package/socket.io

**Comment by julianlam** [comment]
Excellent work @darrachequesne 😄

**Comment by joolswills** [comment]
Please can the npm package be updated with the 1.8.2 version that includes this fix - it's still on 1.7.2 - thanks.

**Comment by joolswills** [comment]
ignore my comment - i see socket.io 1.7.2 includes engine.io 1.8.2

**Comment by vpxavier** [comment]
hello, is this added to Nginx 1.7.3?
Thanks a lot

**Pull request merged**
