### PR TITLE
ws 0.8.0

### PR DESCRIPTION
**Pull request by johanneswuerbach**
iojs 3 compatibility

Related https://github.com/socketio/engine.io-client/pull/411

### CODE REVIEW

**Comment by rmg** [comment]
Looks like it won't be as easy as just updating the version in package.json :-(

To save the digging, the failure on Travis is on this line:
https://github.com/socketio/engine.io/blob/a4dcf1958b53ce15b74b783730e557a9e131eafa/test/server.js#L2204

**Comment by Nibbler999** [comment]
The test failure is unrelated.

**Comment by shinnn** [comment]
@Nibbler999 is right.

**Comment by CxRes** [comment]
@rauchg: Can you please fix this asap. It is holding a lot of us back!!!!!!

**Comment by johanneswuerbach** [comment]
Rebased and passing now :-)

**Comment by rmg** [comment]
Since node-v4.0.0 was just released, this is now even more useful to land/release.

**Comment by kriswill** [comment]
+1  This is blocking the world for a lot of people.

**Comment by 3went2** [comment]
+1 This is blocking the world for a lot of people.

**Comment by lygstate** [comment]
That's a lot of annoy. ws are failed to much.

**Comment by iamstarkov** [comment]
So what about bringing socketio to the nodejs@4.0?

**Comment by SpainTrain** [comment]
Restating the obvious: Until this lands, engine.io and its dependents will be uninstallable under node v4.0.0 (latest stable node).

@rauchg @nkzawa can you please merge and release this update?  That would be so  :heart: 

FWIW, in addition to breaking dependent packages, this is causing administrative overhead for the maintainers of your dependencies due to users filing false positive issues (e.g. https://github.com/websockets/bufferutil/issues/15, https://github.com/websockets/utf-8-validate/issues/13)

**Comment by johanneswuerbach** [comment]
Yeah, looks like it was bumped now.

**Comment by SpainTrain** [comment]
Don't see it on master - https://github.com/socketio/engine.io/blob/master/package.json#L29

**Comment by johanneswuerbach** [comment]
Strange looks like https://github.com/socketio/engine.io/compare/1.5.3...master it was only bumped in a tag

**Comment by marcelaraujo** [comment]
https://github.com/socketio/engine.io/blob/1.5.3-patch/package.json

???

**Comment by marcelaraujo** [comment]
https://github.com/socketio/engine.io-client/issues/420

:(

**Comment by SpainTrain** [comment]
The package in the npm registry has the correct `package.json`, so `npm i` works.

Thanks @rauchg!

**Comment by marcelaraujo** [comment]
@SpainTrain Which version are you used?

**Comment by SpainTrain** [comment]
> @SpainTrain Which version are you used?

```
$ npm cache clean
$ npm info engine.io version
1.5.3

$ npm info engine.io dependencies
 
{ base64id: '0.1.0',
  debug: '1.0.3',
  'engine.io-parser': '1.2.1',
  ws: '0.8.0' }
```

**Comment by marcelaraujo** [comment]
Tks sir!

**Comment by nkzawa** [comment]
Fixed https://github.com/socketio/engine.io/commit/1a115d349310f418eabbe8cfc99702cdeeecdfa7

**Pull request closed without merging**
