### PR TITLE
Implementing #576 connection_dropped event with reason and context

### PR DESCRIPTION
**Pull request by Khez**
### The kind of change this PR does introduce

* [ ] a bug fix
* [x] a new feature
* [x] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour
There's currently no way of knowing when a connection is dropped due to the internal validation of engine.io

### New behaviour
Added a new event `connection_dropped` with context for the various scenarios that cause a connection to be dropped

### Other information (e.g. related issues)
The PR is for the 3.4.x branch. Once we get this PR validated, we can add the same event to 3.5.x and 4.x branches

Engine.IO: https://github.com/socketio/engine.io/issues/576
Socket.IO: https://github.com/socketio/socket.io/issues/3819

### Review

1. Is there a hard need for [allowRequest to be able to dictate the message for the error page](https://github.com/socketio/engine.io/blob/4.1.1/test/server.js#L86) ?
2. Is the [res check really needed](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L492)?
    - It's set as `req.res` or passed directly in all callbacks?
    - If it can be undefined, why isn't it checked in the [FORBIDDEN branch](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L482)?
3. Updated the signature of [verify's callback](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L308) since it is [private](https://github.com/socketio/engine.io/blob/master/lib/server.js#L100)
    - Does anyone mind the `errorCode !== undefined` check in handleUpgrade and handleRequest ?
    - It's necessary since [UNKNOWN_TRANSPORT](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L452) is 0
4. Not particularly keen on BAD_REQUEST having a sub-name property, but adding new error codes would need to skip [UNSUPPORTED_PROTOCOL_VERSION](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L458) used in 4.x
5. Not particularly keen on the context property being "dynamic". We could update to use `new Error()`, but I've seen that's not particularly common.

### CODE REVIEW

**Comment by darrachequesne** [comment]
> 1. Is there a hard need for [allowRequest to be able to dictate the message for the error page](https://github.com/socketio/engine.io/blob/4.1.1/test/server.js#L86) ?

No, but updating this would be a breaking change I think.

> 2. Is the [res check really needed](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L492)?
>    - It's set as `req.res` or passed directly in all callbacks?
>    - If it can be undefined, why isn't it checked in the [FORBIDDEN branch](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L482)?

It looks like this check is indeed useless (added in https://github.com/socketio/engine.io/commit/73e579a501228226adb38f61da25b267e216b6d6, for reference).

> 3. Updated the signature of [verify's callback](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L308) since it is [private](https://github.com/socketio/engine.io/blob/master/lib/server.js#L100)
    - Does anyone mind the `errorCode !== undefined` check in handleUpgrade and handleRequest ?
    - It's necessary since [UNKNOWN_TRANSPORT](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L452) is 0

No problem :+1: 

> 4. Not particularly keen on BAD_REQUEST having a sub-name property, but adding new error codes would need to skip [UNSUPPORTED_PROTOCOL_VERSION](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L458) used in 4.x

Yes, the subtype is indeed necessary and adding new error codes would require a major bump.

> 5. Not particularly keen on the context property being "dynamic". We could update to use `new Error()`, but I've seen that's not particularly common.

How about the following API:

```js
engine.on("connection_error", (err) => {
  console.log(err.message); // Bad handshake method
  console.log(err.code); // BAD_HANDSHAKE_METHOD
  console.log(err.req); // the request object
  // additional properties depending on the type of error
});
```

Which feels closer to classic Node.js error handling (https://nodejs.org/api/errors.html). What do you think?

**Comment by Khez** [comment]
> 1. Is there a hard need for [allowRequest to be able to dictate the message for the error page](https://github.com/socketio/engine.io/blob/4.1.1/test/server.js#L86) ?

Going to leave it as is. But I'm glad the conversation was started!

> 2. Is the [res check really needed](https://github.com/socketio/engine.io/blob/4.1.1/lib/server.js#L492)?

It seems [req.res](https://github.com/socketio/engine.io/blob/73e579a501228226adb38f61da25b267e216b6d6/lib/server.js#L225) existed back then too! It was added rather deliberately and the call graph didn't change by a lot. I can't see a reason for it back then either... Kind of afraid to remove it and it makes me want to add it to the forbidden branch :?

Alternatively, mind if we pluck it to the top of the function?
```javascript
if (res === undefined) {
    debug('Could not abort connection due to missing response object (%s)', code);
    return;
}
``` 
We get a log, but I'm uncertain how we can track when/where/if this actually happens...

> 5. How about the following API:

I like the ideea of having a standard type and the request object. You could relate other app specific data in your handler.

- Would `context.message` be one of the `Server.errorMessages` strings ?
- Would `context.code` be the `code` result from `allowRequest` or would that result be suited as another property ?
- As an additional property for TRANSPORT_HANDSHAKE_ERROR we would have the underlying error in `context.error` ?

If we're in agreement, I can make the changes, update the tests and prepare for the 3.5 and 4.x branches :)

**Comment by darrachequesne** [comment]
> Alternatively, mind if we pluck it to the top of the function?

Sounds good to me :+1: 

> Would context.message be one of the Server.errorMessages strings ?

Yes

> Would context.code be the code result from allowRequest or would that result be suited as another property ?

For the `allowRequest`  case, we could use:

- message: user-defined message ("thou shall not pass") or "Forbidden" by default
- code: `FORBIDDEN` (from `Server.errors`)

> As an additional property for TRANSPORT_HANDSHAKE_ERROR we would have the underlying error in context.error ?

I think we could use `FORBIDDEN` (from `Server.errors`) in that case.

What is your opinion?

**Comment by Khez** [comment]
Latest commit should cover it.

Had to move the allowRequest from "code" to "message" which kind of makes more sense in the way the old api worked for it.

**Comment by Khez** [comment]
@darrachequesne mild ping

Can we continue with a PR to the other branches of engine.io and socket.io ?

**Comment by darrachequesne** [comment]
Merged as https://github.com/socketio/engine.io/commit/7096e98a02295a62c8ea2aa56461d4875887092d and included in `engine.io@5.1.0`. Thanks a lot :+1:

**Comment by Khez** [comment]
Sorry you had to redo the code, uncertain why that was necessary.

Any chance this can get back-ported v4 and v3 ?

**Comment by darrachequesne** [comment]
> Sorry you had to redo the code, uncertain why that was necessary.

There was a lot of modifications when merging into master, due to the linting by prettier (https://github.com/socketio/engine.io/commit/33564b2391e0d4393b636bbb956ba9a8ae5a38e0). That's why I manually imported your changes.

> Any chance this can get back-ported v4 and v3 ?

I'd rather leave those branches in maintenance mode, with only bug fixes. Any particular reason you'd like it to be back-ported?

**Pull request closed without merging**
