### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by djoq**
Update to current version of ws package.

### The kind of change this PR does introduce

* [x] a bug fix
* [ ] a new feature
* [ ] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour
Fails with TypeError: Cannot read property 'isValidUTF8' of undefined using the old package.

### New behaviour
The error does not throw.

### Other information (e.g. related issues)
http://stackoverflow.com/questions/42498858/node-js-and-socket-io-utf8-validation-typeerror-coming-from-ws

### CODE REVIEW

**Comment by billouboq** [comment]
We can't bump ws right now without doing a major release because ws 2.0.0 dropped older node support (0.10 and 0.12)

**Comment by Nibbler999** [comment]
You are probably using the wrong version of utf-8-validate. ws 1.x uses utf-8-validate 1.2.x

**Comment by djoq** [comment]
not sure, it's a deep tree of departure. I am forced to build a version 1.8.3 locally or it's utf and validation error mayhem, this is only way I can build both mac Linux. Where are those versions specified?

**Comment by Nibbler999** [comment]
https://github.com/websockets/ws/blob/v1.x/package.json#L37

If you install utf-8-validate 1.2.x in the ws node_modules directory you should be fine.

**Comment by djoq** [comment]
It is fine, just engine.io is stale and ws is at 2.2

**Pull request merged**
