### PR TITLE
docs: remove the extra bracket in README

### PR DESCRIPTION
**Pull request by lmk123**
### The kind of change this PR does introduce

* [ ] a bug fix
* [ ] a new feature
* [x] an update to the documentation
* [ ] a code change that improves performance
* [ ] other

### Current behaviour

As shown in the figure below, there is an extra bracket `)` in README

image

### New behaviour

It looks neater without the extra parentheses. I have a little bit of OCD :joy:

image

### CODE REVIEW

**Comment by darrachequesne** [comment]
@lmk123 good catch, thanks!

**Comment by Psoffie009** [comment]
> ### The kind of change this PR does introduce
> * [ ]  a bug fix
> * [ ]  a new feature
> * [x]  an update to the documentation
> * [ ]  a code change that improves performance
> * [ ]  other
> 
> ### Current behaviour
> As shown in the figure below, there is an extra bracket `)` in README
> 
> image
> 
> ### New behaviour
> It looks neater without the extra parentheses. I have a little bit of OCD 😂
> 
> image
> 
> ### Other information (e.g. related issues)

**Comment by Psoffie009** [comment]
> > ### The kind of change this PR does introduce
> > 
> > * [x]   a bug fix
> > * [x]   a new feature
> > * [x]   an update to the documentation
> > * [ ]   a code change that improves performance
> > * [x]   other
> > 
> > ### Current behaviour
> > As shown in the figure below, there is an extra bracket `)` in README
> > image
> > ### New behaviour
> > It looks neater without the extra parentheses. I have a little bit of OCD 😂
> > image
> > ### Other information (e.g. related issues)

**Comment by Psoffie009** [comment]
> > > ### The kind of change this PR does introduce
> > > 
> > > * [x]    a bug fix
> > > * [x]    a new feature
> > > * [x]    an update to the documentation
> > > * [x]    a code change that improves performance
> > > * [x]    other
> > > 
> > > ### Current behaviour
> > > As shown in the figure below, there is an extra bracket `)` in README
> > > image
> > > ### New behaviour
> > > It looks neater without the extra parentheses. I have a little bit of OCD 😂
> > > image
> > > ### Other information (e.g. related issues)

**Pull request merged**
